version: '3.5'

services:
  # api:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run dev
  db:
    image: postgres:11-alpine
    volumes:
      - myvol1:/var/lib/postgresql/data
    ports: "5432:5432"