version: '3.5'

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    # networks:
    #   - app
# networks:
#   app:
#     name: myapp_network