version: '3.5'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    networks:
      - app
networks:
  app:
    name: myapp_network