# run with `docker-compose up -d`
# to unmount volume and reinitialize schema/data, run with `docker-compose down -v`
version: '3.5'
services:
  api:
    build: .
    restart: always
    volumes:
      #Mount application code
      - ./:/app
    env_file:
      #Use env file instead of Spring profiles properties
      - local_properties.env
    ports:
      - 8080:8080
    command: nodemon -e java --watch src --exec 'mvn spring-boot:run || touch src/'
# Example DB Service
#   db:
#     image: postgres:10
#     container_name: db
#     networks: 
#       - appnet
#     environment:
#       - POSTGRES_DB=appdb
#       - POSTGRES_USER=myApp
#       - POSTGRES_PASSWORD=ppaym
#     # volumes:
#       # - postgresql_data:/var/lib/postgresql/data
#     networks:
#       - springbootapp

# Example use of networks
# networks:
#   springbootapp:
#     name: springbootapp_network

# For you Windows people =(
# volumes:
#   db_data: